# Generated by Django 3.2.15 on 2022-10-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_others'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Others',
        ),
    ]
