# Generated by Django 3.2.15 on 2022-10-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_delete_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='short_desc',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
