# Generated by Django 3.2.15 on 2022-10-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_movie_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='short_desc',
            field=models.CharField(max_length=50),
        ),
    ]
